---
title: "Installation von R-Paketen"
author: "Andreas Blaette"
date: ""
output: html_document
---


Installation unter Windows
============================

Installation von R
------------------

Download der Datei R-3.2.0-win.exe von:
http://cran.r-project.org/bin/windows/base/
  
Dann "Ausführen", um Installation zu beginnen. Als Zielverzeichnis für die Installation wurde vorgeschlagen:
C:\Program Files\R\R-3.2.0
Dies und alle weiteren Standardeinstellungen können für die Installation bestätigt werden.


Installation von RStudio
------------------------
  
Download der *.exe-Datei für Windows-Installation von:
http://www.rstudio.com/products/rstudio/download/
Durch Ausführen der Datei startet Installation. Standardeinstellungen können übernommen werden.


Installation von Rtools
-----------------------
Download von:
http://cran.r-project.org/bin/windows/Rtools/index.html
Bei der Installation habe ich auch die 64bit-Version von tcl/tk für die Installation vorgesehen und
in die Pfad-Umgebungsvariable den Pfad zur R-Installation vorgesehen.


Installation von Paketen
========================
  
GLES
----

```{r eval=FALSE}
# Installation des devtools-Pakets
install.packages("devtools") 

# Laden des devtools-Pakets
library(devtools)

# installation des gles-Pakets
install.packages("gles", repos = "https://134.91.37.242/packages")
```

ESS
---

```{r eval=FALSE}
install.packages("devtools") 
library(devtools)
install_url("http://polmine.sowi.uni-due.de/R/ess_0.1.0.tar.gz")
library(ess)
data(ess6)
```

ALLBUS
------

```{r eval=FALSE}
# install.packages("devtools") 
# library(devtools)
install_url("http://polmine.sowi.uni-due.de/R/allbus_0.1.0.tar.gz")
library(allbus)
data(allbus2012)
```


