---
title: "Kurzeinführung in die Arbeit mit dem GLES-Datensatz"
author: "Andreas Blaette"
date: "18. Juni 2015"
output: html_document
---

Initialisierung
===============


```{r}
rm(list=ls(all=TRUE))
library(gles)
data(bt2009) # Datensatz für 2009
data(bt2013)
data(nrw2010)
data(nrw2012)
```



Aufrufen der Dokumentation der Fragebögen
=========================================

```{r}
questionnaire("bt2009")
questionnaire("bt2013")
questionnaire("nrw2010")
questionnaire("nrw2012")
```

Knifflig: Die Gewichtung von Variablen
======================================

```{r}
gewicht <- bt2013[,"w_trow"] # hier ist das Gewicht
geschlecht <- bt2013[,"vn1"] # das Geschlecht
wahlabsicht <- bt2013[,"v11aa"] # beabsichtigte Parteiwahl
wahlabsichtTab <- tapply(gewicht, wahlabsicht, sum)
```

```{r}
bt2013subset <- bt2013[, c("v11aa", "vn1", "w_trow")]
colnames(bt2013subset) <- c("wahlabsicht", "geschlecht", "gewicht")
wahlabsichtGeschlecht <- xtabs(gewicht~wahlabsicht+geschlecht, data=bt2013subset)
wahlabsichtMaenner <- wahlabsichtGeschlecht[,1] / sum(wahlabsichtGeschlecht[,1])
wahlabsichtFrauen <- wahlabsichtGeschlecht[,2] / sum(wahlabsichtGeschlecht[,2])


# die schnellere, schwerer zu durchschauenden Variante ...
wahlabsichtGewichtet <- apply(wahlabsichtGeschlecht, 2, function(x) x / sum(x))
rowsToDrop <- c(which(rownames(wahlabsichtGewichtet) %in% c("CDU", "CSU")))
wahlabsichtGewichtet <- wahlabsichtGewichtet[-rowsToDrop,]
wahlabsichtProzent <- round(wahlabsichtGewichtet * 100, 2)
par(mar=c(8,3,1,1))
barplot(t(wahlabsichtProzent), beside=T, las=2, col=c("blue", "red"))
legend(x=18, y=30, legend=c("männlich", "weiblich"), col=c("blue", "red"), fill=T)
```
