Lösung zu den Aufgaben 
----------------------
  
Aufgabe: Durchschnittsgröße von Männern und Frauen im Vergleich...

__Die Daten__

```{r}
size <- c(
  c(pawel=NA, maassen=169, gansohr=182, sivananda=169, koenig=178, peters=179, schmidt=179),
  c(streich=164, riedl=182, neuenhaus=193, klaessen=183, ospanov=170, wulfgram=182, thiemann=173),
  c(gehlhar=180, hohl=171, motte=175, schmelter=169, heidebrecht=183),
  c(tegeler=184, baudisch=192, arens=186, wegscheider=184)
)

male <- c(
  c(pawel=TRUE, maassen=FALSE, gansohr=TRUE, sivananda=TRUE, koenig=FALSE, peters=FALSE, schmidt=TRUE),
  c(streich=FALSE, riedl=TRUE, neuenhaus=TRUE, klaessen=TRUE, ospanov=TRUE, wulfgram=TRUE, thiemann=TRUE),
  c(gehlhar=TRUE, hohl=FALSE, motte=TRUE, schmelter=FALSE, heidebrecht=TRUE),
  c(tegeler=FALSE, arens=TRUE, baudisch=TRUE, wegscheider=TRUE)
)
```

__Lösung 1: Indizierung des size-Vektors über Namen__

```{r}
# Variante A: mit Zwischenschritten ...
posMen <- which(male == TRUE) # das ergibt Positionen im Vektor
namesMen <- names(posMen) # uns interessieren aber die Namen
sizeMen <-  size[namesMen] # mit den Namen wird der size-Vektor indiziert 
mean(sizeMen, na.rm = TRUE) # und jetzt: die Mittelwertberechnung

# Variante B: in einem Rutsch (am Anfang bisschen schlecht lesbar)
mean(size[names(which(male == TRUE))], na.rm=TRUE)
```

__Lösung 2: Indizierung über Positionen im Vektor__

```{r}
sizeReordered <- size[order(names(size))] # alphabetische Sortierung
maleReordered <- male[order(names(size))] # alphabetische Sortierung

posMen <- which(maleReordered == FALSE)
mean(sizeReordered[posMen], na.rm=TRUE)
```


__Balkendiagramm__

```{r}
barplot(size[order(size, decreasing=T)], las=2)
````
